// src/views/attributes/privacy/AddressCorrelationDetails.svelte
<script lang="ts">
	// Types/constants
	import type { AddressCorrelationValue } from '@/schema/attributes/privacy/address-correlation'
	import type { WalletAddressLinkableBy } from '@/schema/attributes/privacy/address-correlation'
	import type { FullyQualifiedReference } from '@/schema/reference'
	import type { RatedWallet } from '@/schema/wallet'
	import type { NonEmptyArray } from '@/types/utils/non-empty'
	import { ContentType } from '@/types/content'

	type LeakInfo = {
		key: string
		value: string
	}

	type LeaksListItem = {
		sourceName: string
		linkables: NonEmptyArray<WalletAddressLinkableBy>
		linkableInfos: LeakInfo[]
		refs: FullyQualifiedReference[]
		entity: WalletAddressLinkableBy['by']
	}

	// Props
	let {
		wallet,
		value,
		linkables,
	}: {
		wallet: RatedWallet
		value: AddressCorrelationValue
		linkables?: NonEmptyArray<WalletAddressLinkableBy> | undefined
	} = $props()

	// Functions
	import { compareUserInfo, userInfoName } from '@/schema/features/privacy/data-collection'
	import { mergeRefs } from '@/schema/reference'
	import { isUrl } from '@/schema/url'
	import { nonEmptyGet, nonEmptySorted } from '@/types/utils/non-empty'

	const joinedListText = (
		items: LeakInfo[],
		separator = ', ',
		lastSeparator = ' and ',
	): string => (
		items
			.map((item, index) => (
				item.value + (
					index === items.length - 2 ?
						lastSeparator 
					: index !== items.length - 1 ?
						separator 
					:
						''
				)
			))
			.join('')
	)

	// Components
	import Typography from '@/components/Typography.svelte'
</script>

{#if !linkables}
	<Typography 
		content={{
			contentType: ContentType.MARKDOWN,
			markdown: 'By default, **{{WALLET_NAME}}** allows your wallet address to be correlated with your personal information:'
		}}
		strings={{ 
			WALLET_NAME: wallet.metadata.displayName,
			WALLET_PSEUDONYM_SINGULAR: wallet.metadata.pseudonymType?.singular ?? null,
			WALLET_PSEUDONYM_PLURAL: wallet.metadata.pseudonymType?.plural ?? null,
		}}
	/>
{:else}
	{@const sortedLinkables = nonEmptySorted(
		linkables,
		(linkableA: WalletAddressLinkableBy, linkableB: WalletAddressLinkableBy) => (
			linkableA.by === 'onchain' ?
				1
			: linkableB.by === 'onchain' ?
				-1
			:
				compareUserInfo(linkableA.info, linkableB.info)
		),
		true,
	)}
	
	{@const bySource = (() => {
		const map = new Map<string, NonEmptyArray<WalletAddressLinkableBy>>()
		
		for (const linkable of sortedLinkables) {
			const sourceName = typeof linkable.by === 'string' ? linkable.by : linkable.by.name
			const forSource = map.get(sourceName)
			if (forSource === undefined) {
				map.set(sourceName, [linkable] as NonEmptyArray<WalletAddressLinkableBy>)
			} else {
				forSource.push(linkable)
			}
		}
		
		return map
	})()}
	
	{@const leaksList = (() => {
		const list: LeaksListItem[] = []
		
		bySource.forEach((linkables, sourceName) => {
			const linkableInfos: LeakInfo[] = linkables.map(linkable => ({
				key: linkable.info,
				value: userInfoName(linkable.info).long
			}))
			const refs = mergeRefs(...linkables.flatMap(linkable => linkable.refs))
			const entity = nonEmptyGet(linkables).by
			
			list.push({
				sourceName,
				linkables,
				linkableInfos,
				refs,
				entity
			})
		})
		
		return list
	})()}
	
	{@const leaksText = leaksList.map(leak => (
		leak.entity === 'onchain' ?
			`- An onchain record permanently associates your **${joinedListText(leak.linkableInfos)}** with your wallet address.`
		: typeof leak.entity !== 'string' ?
			(() => {
				const privacyPolicyText = (
					isUrl(leak.entity.privacyPolicy) ?
						` ([Privacy policy](${typeof leak.entity.privacyPolicy === 'string' ? leak.entity.privacyPolicy : leak.entity.privacyPolicy.url}))`
					:
						''
				)
				return `- **${leak.entity.name}**${privacyPolicyText} may link your wallet address to your **${joinedListText(leak.linkableInfos)}**.`
			})()
		:
			`- **${leak.entity}** may link your wallet address to your **${joinedListText(leak.linkableInfos)}**.`
	)).join('\n')}
	
	<Typography 
		content={{
			contentType: ContentType.MARKDOWN,
			markdown: `By default, **{{WALLET_NAME}}** allows your wallet address to be correlated with your personal information:

${leaksText}`
		}}
		strings={{ 
			WALLET_NAME: wallet.metadata.displayName,
			WALLET_PSEUDONYM_SINGULAR: wallet.metadata.pseudonymType?.singular ?? null,
			WALLET_PSEUDONYM_PLURAL: wallet.metadata.pseudonymType?.plural ?? null,
		}}
	/>
{/if}

// src/ui/molecules/attributes/privacy/AddressCorrelationDetails.tsx
import { Typography } from '@mui/material'
import type React from 'react'

import { subsectionWeight } from '@/components/constants'
import type { WalletAddressLinkableBy } from '@/schema/attributes/privacy/address-correlation'
import { compareUserInfo, userInfoName } from '@/schema/features/privacy/data-collection'
import { mergeRefs } from '@/schema/reference'
import { isUrl } from '@/schema/url'
import type { AddressCorrelationDetailsProps } from '@/types/content/address-correlation-details'
import { type NonEmptyArray, nonEmptyGet, nonEmptySorted } from '@/types/utils/non-empty'
import { EntityLink } from '@/ui/atoms/EntityLink'

import { ExternalLink } from '../../../atoms/ExternalLink'
import { JoinedList } from '../../../atoms/JoinedList'
import { ReferenceLinks } from '../../../atoms/ReferenceLinks'
import { WrapRatingIcon } from '../../../atoms/WrapRatingIcon'

export function AddressCorrelationDetails({
	wallet,
	value,
	linkables,
}: AddressCorrelationDetailsProps): React.JSX.Element {
	const bySource = new Map<string, NonEmptyArray<WalletAddressLinkableBy>>()

	for (const linkable of nonEmptySorted(
		linkables,
		(linkableA: WalletAddressLinkableBy, linkableB: WalletAddressLinkableBy) => {
			if (linkableA.by === 'onchain') {
				return 1
			}

			if (linkableB.by === 'onchain') {
				return -1
			}

			return compareUserInfo(linkableA.info, linkableB.info)
		},
		true,
	)) {
		const sourceName = typeof linkable.by === 'string' ? linkable.by : linkable.by.name
		const forSource = bySource.get(sourceName)

		if (forSource === undefined) {
			bySource.set(sourceName, [linkable])
		} else {
			forSource.push(linkable)
		}
	}
	const leaksList: React.ReactNode[] = []

	bySource.forEach((linkables, sourceName) => {
		const linkableInfos = (
			<JoinedList
				data={linkables.map(linkable => ({
					key: linkable.info,
					value: <strong>{userInfoName(linkable.info).long}</strong>,
				}))}
			/>
		)
		const refs = mergeRefs(...linkables.flatMap(linkable => linkable.refs))
		const entity = nonEmptyGet(linkables).by

		if (entity === 'onchain') {
			leaksList.push(
				<li key={sourceName}>
					<Typography>
						An onchain record permanently associates your {linkableInfos} with your wallet address.{' '}
						<ReferenceLinks references={refs} />
					</Typography>
				</li>,
			)

			return
		}

		leaksList.push(
			<li key={sourceName}>
				<Typography>
					<EntityLink entity={entity} />{' '}
					{isUrl(entity.privacyPolicy) ? (
						<>
							{' ('}
							<ExternalLink url={entity.privacyPolicy} defaultLabel='Privacy policy' />
							{')'}
						</>
					) : null}{' '}
					may link your wallet address to your {linkableInfos}. <ReferenceLinks references={refs} />
				</Typography>
			</li>,
		)
	})

	return (
		<>
			<WrapRatingIcon rating={value.rating}>
				<Typography fontWeight={subsectionWeight}>
					By default, {wallet.metadata.displayName} allows your wallet address to be correlated with
					your personal information:
				</Typography>
				<ul style={{ paddingLeft: '1.5rem', marginBottom: '0px', fontWeight: subsectionWeight }}>
					{leaksList}
				</ul>
			</WrapRatingIcon>
		</>
	)
}
