// src/views/attributes/security/ScamAlertDetails.svelte
<script lang="ts">
	// Types/constants
	import type { ScamPreventionValue } from '@/schema/attributes/security/scam-prevention'
	import { isSupported } from '@/schema/features/support'
	import { toFullyQualified } from '@/schema/reference'
	import type { RatedWallet } from '@/schema/wallet'
	import { ContentType } from '@/types/content'
	import { commaListFormat } from '@/types/utils/text'

	// Props
	let {
		wallet,
		value,
	}: {
		wallet: RatedWallet
		value: ScamPreventionValue
	} = $props()

	// Components
	import Typography from '@/components/Typography.svelte'
	import ReferenceLinks from '@/views/ReferenceLinks.svelte'
</script>

<Typography
	content={value.shortExplanation}
	strings={{
		WALLET_NAME: wallet.metadata.displayName,
		WALLET_PSEUDONYM_SINGULAR: wallet.metadata.pseudonymType?.singular ?? null,
		WALLET_PSEUDONYM_PLURAL: wallet.metadata.pseudonymType?.plural ?? null,
	}}
/>

{#if value.scamAlerts}
	{@const scamUrlLeaks =
		!value.scamAlerts || !isSupported(value.scamAlerts.scamUrlWarning)
			? []
			: ([
					value.scamAlerts.scamUrlWarning.leaksIp && 'your IP',
					value.scamAlerts.scamUrlWarning.leaksUserAddress && 'your Ethereum address',
					value.scamAlerts.scamUrlWarning.leaksVisitedUrl === 'FULL_URL' &&
						'the full URL of the app',
					value.scamAlerts.scamUrlWarning.leaksVisitedUrl === 'DOMAIN_ONLY' &&
						'the domain name of the app',
				].filter(Boolean) as string[])}

	<ul class="features-list">
		{#if value.sendTransactionWarning?.required}
			<li>
				<Typography
					content={{
						contentType: ContentType.MARKDOWN,
						markdown: isSupported(value.scamAlerts.sendTransactionWarning)
							? `**{{WALLET_NAME}}** helps you stay safe when sending funds by ${
									value.scamAlerts.sendTransactionWarning.newRecipientWarning &&
									value.scamAlerts.sendTransactionWarning.userWhitelist
										? 'warning you when sending funds to an address you have not sent or received funds from in the past, and allowing you to build a contact book of addresses and warning you when sending funds to addresses not in it.'
										: value.scamAlerts.sendTransactionWarning.newRecipientWarning
											? 'warning you when sending funds to an address you have not sent or received funds from in the past.'
											: value.scamAlerts.sendTransactionWarning.userWhitelist
												? 'allowing you to build a contact book of addresses and warning you when sending funds to addresses not in it.'
												: 'providing transaction warnings.'
								}${
									!value.sendTransactionWarning.privacyPreserving
										? ` However, in doing so, it leaks ${commaListFormat(
												[
													value.scamAlerts.sendTransactionWarning.leaksUserIp && 'your IP',
													value.scamAlerts.sendTransactionWarning.leaksUserAddress &&
														'your Ethereum address',
													value.scamAlerts.sendTransactionWarning.leaksRecipient &&
														"the recipient's Ethereum address",
												].filter(Boolean) as string[],
											)} to an external provider which can correlate them.`
										: ''
								}`
							: `**{{WALLET_NAME}}** does not warn you when sending funds to suspicious addresses.`,
					}}
					strings={{ WALLET_NAME: wallet.metadata.displayName }}
				/>

				{#if isSupported(value.scamAlerts.sendTransactionWarning) && value.scamAlerts.sendTransactionWarning.ref}
					<hr />

					<ReferenceLinks
						references={toFullyQualified(value.scamAlerts.sendTransactionWarning.ref)}
					/>
				{/if}
			</li>
		{/if}

		{#if value.contractTransactionWarning?.required}
			{@const contractFeatures = isSupported(value.scamAlerts.contractTransactionWarning)
				? [
						value.scamAlerts.contractTransactionWarning.contractRegistry,
						value.scamAlerts.contractTransactionWarning.previousContractInteractionWarning,
						value.scamAlerts.contractTransactionWarning.recentContractWarning,
					].filter(Boolean)
				: []}

			<li>
				<Typography
					content={{
						contentType: ContentType.MARKDOWN,
						markdown: isSupported(value.scamAlerts.contractTransactionWarning)
							? `**{{WALLET_NAME}}** helps you stay safe when doing onchain transactions by ${
									contractFeatures.length > 1
										? `:${[
												value.scamAlerts.contractTransactionWarning.contractRegistry &&
													`Checking the contract or transaction data against a database of known scams`,
												value.scamAlerts.contractTransactionWarning
													.previousContractInteractionWarning &&
													`Warning you when interacting with a contract you have not interacted with before`,
												value.scamAlerts.contractTransactionWarning.recentContractWarning &&
													`Warning you when interacting with a contract that has only recently been created onchain`,
											]
												.filter(Boolean)
												.map(listItem => `\n* ${listItem}`)
												.join('')}`
										: value.scamAlerts.contractTransactionWarning.contractRegistry
											? 'checking the contract or transaction data against a database of known scams.'
											: value.scamAlerts.contractTransactionWarning
														.previousContractInteractionWarning
												? 'warning you when interacting with a contract you have not interacted with before.'
												: value.scamAlerts.contractTransactionWarning.recentContractWarning
													? 'warning you when interacting with a contract that has only recently been created onchain.'
													: 'providing contract warnings.'
								}${
									!value.contractTransactionWarning.privacyPreserving
										? ` However, in doing so, it leaks ${commaListFormat(
												[
													value.scamAlerts.contractTransactionWarning.leaksUserIp && 'your IP',
													value.scamAlerts.contractTransactionWarning.leaksUserAddress &&
														'your Ethereum address',
													value.scamAlerts.contractTransactionWarning.leaksContractAddress &&
														'the contract address',
												].filter(Boolean) as string[],
											)} to an external provider which can correlate them ahead of the transaction being submitted.`
										: ''
								}`
							: `**{{WALLET_NAME}}** does not warn you when making arbitrary onchain transactions.`,
					}}
					strings={{ WALLET_NAME: wallet.metadata.displayName }}
				/>

				{#if isSupported(value.scamAlerts.contractTransactionWarning) && value.scamAlerts.contractTransactionWarning.ref}
					<hr />

					<ReferenceLinks
						references={toFullyQualified(value.scamAlerts.contractTransactionWarning.ref)}
					/>
				{/if}
			</li>
		{/if}

		{#if value.scamUrlWarning?.required}
			<li>
				<Typography
					content={{
						contentType: ContentType.MARKDOWN,
						markdown: isSupported(value.scamAlerts.scamUrlWarning)
							? `**{{WALLET_NAME}}** helps you stay safe when connecting to onchain apps by checking its URL against a set of known scam apps.${
									!value.scamUrlWarning.privacyPreserving && scamUrlLeaks.length > 0
										? ` However, in doing so, it leaks ${commaListFormat(scamUrlLeaks)} to an external provider${
												scamUrlLeaks.length > 1 ? ' which can correlate them' : ''
											}.`
										: ''
								}`
							: `**{{WALLET_NAME}}** does not check URLs against known scam sites.`,
					}}
					strings={{ WALLET_NAME: wallet.metadata.displayName }}
				/>

				{#if isSupported(value.scamAlerts.scamUrlWarning) && value.scamAlerts.scamUrlWarning.ref}
					<hr />

					<ReferenceLinks references={toFullyQualified(value.scamAlerts.scamUrlWarning.ref)} />
				{/if}
			</li>
		{/if}
	</ul>
{/if}

<style>
	.features-list {
		margin: 0.5rem 0 0 0;
		padding-left: 1.5rem;
		> li + li {
			margin-top: 1rem;
		}

		> li {
			> :global(* + *) {
				margin-top: 0.5rem;
			}
		}
	}
</style>

// src/ui/molecules/attributes/security/ScamAlertDetails.tsx
import { Typography } from '@mui/material'
import type React from 'react'

import { subsectionWeight } from '@/components/constants'
import { isSupported } from '@/schema/features/support'
import { toFullyQualified } from '@/schema/reference'
import type { ScamAlertDetailsProps } from '@/types/content/scam-alert-details'
import { commaListFormat, trimWhitespacePrefix } from '@/types/utils/text'
import { ReferenceLinks } from '@/ui/atoms/ReferenceLinks'
import { RenderTypographicContent } from '@/ui/atoms/RenderTypographicContent'

import { WrapRatingIcon } from '../../../atoms/WrapRatingIcon'

function listOrSingleText(prefix: string, items: Array<string | null>): React.ReactNode {
	const filtered = items.filter(item => item !== null)

	if (filtered.length === 1) {
		const stripped = trimWhitespacePrefix(filtered[0]).trim()

		return (
			<Typography variant='body1'>
				{prefix} {stripped[0].toLocaleLowerCase() + stripped.slice(1)}.
			</Typography>
		)
	}

	return (
		<>
			<Typography variant='body1'>{prefix}:</Typography>
			<ul>
				{filtered.map(item => {
					const stripped = trimWhitespacePrefix(item).trim()

					return (
						<li key={stripped}>
							<Typography variant='body1'>
								{stripped[0].toUpperCase() + stripped.slice(1)}.
							</Typography>
						</li>
					)
				})}
			</ul>
		</>
	)
}

export function ScamAlertDetails({ wallet, value }: ScamAlertDetailsProps): React.JSX.Element {
	if (value.scamAlerts === null) {
		throw new Error('Cannot render ScamAlertDetails for undefined data')
	}

	const scamUrlLeaks: string[] = isSupported(value.scamAlerts.scamUrlWarning)
		? [
				value.scamAlerts.scamUrlWarning.leaksIp ? 'your IP' : null,
				value.scamAlerts.scamUrlWarning.leaksUserAddress ? 'your Ethereum address' : null,
				((): string | null => {
					switch (value.scamAlerts.scamUrlWarning.leaksVisitedUrl) {
						case 'FULL_URL':
							return 'the full URL of the app'
						case 'DOMAIN_ONLY':
							return 'the domain name of the app'
						case 'PARTIAL_HASH_OF_DOMAIN':
							return null
						case 'NO':
							return null
					}
				})(),
			].filter(val => val !== null)
		: []

	return (
		<>
			<WrapRatingIcon rating={value.rating}>
				<Typography fontWeight={subsectionWeight}>
					<RenderTypographicContent
						content={value.shortExplanation}
						strings={{
							WALLET_NAME: wallet.metadata.displayName,
							WALLET_PSEUDONYM_SINGULAR:
								wallet.metadata.pseudonymType === undefined
									? null
									: wallet.metadata.pseudonymType.singular,
							WALLET_PSEUDONYM_PLURAL:
								wallet.metadata.pseudonymType === undefined
									? null
									: wallet.metadata.pseudonymType.plural,
						}}
					/>
				</Typography>
			</WrapRatingIcon>
			<div>
				<ul>
					{value.sendTransactionWarning.required && (
						<li>
							{isSupported(value.scamAlerts.sendTransactionWarning) ? (
								<>
									{listOrSingleText(
										`${wallet.metadata.displayName} helps you stay safe when sending funds by`,
										[
											value.scamAlerts.sendTransactionWarning.newRecipientWarning
												? `
													warning you when sending funds to an address you have
													not sent or received funds from in the past
												`
												: null,
											value.scamAlerts.sendTransactionWarning.userWhitelist
												? `
													Allowing you to build a contact book of addresses and
													warning you when sending funds to addresses not in it
												`
												: null,
										],
									)}
									{!value.sendTransactionWarning.privacyPreserving && (
										<Typography variant='body1'>
											However, in doing so, it leaks{' '}
											{commaListFormat([
												value.scamAlerts.sendTransactionWarning.leaksUserIp ? 'your IP' : null,
												value.scamAlerts.sendTransactionWarning.leaksUserAddress
													? 'your Ethereum address'
													: null,
												value.scamAlerts.sendTransactionWarning.leaksRecipient
													? "the recipient's Ethereum address"
													: null,
											])}{' '}
											to an external service which can correlate them.
										</Typography>
									)}
									{toFullyQualified(value.scamAlerts.sendTransactionWarning.ref).length > 0 && (
										<ReferenceLinks
											references={toFullyQualified(value.scamAlerts.sendTransactionWarning.ref)}
											explanation='References:'
										/>
									)}
								</>
							) : (
								<Typography variant='body1'>
									{wallet.metadata.displayName} does not warn you when sending funds to suspicious
									addresses.
								</Typography>
							)}
						</li>
					)}
					{value.contractTransactionWarning.required && (
						<li>
							{isSupported(value.scamAlerts.contractTransactionWarning) ? (
								<>
									{listOrSingleText(
										`${wallet.metadata.displayName} helps you stay safe when doing onchain transactions by`,
										[
											value.scamAlerts.contractTransactionWarning.contractRegistry
												? `
													Checking the contract or transaction data against a database of known scams
												`
												: null,
											value.scamAlerts.contractTransactionWarning.previousContractInteractionWarning
												? `
													Warning you when interacting with a contract you have not interacted with
													before
												`
												: null,
											value.scamAlerts.contractTransactionWarning.recentContractWarning
												? `
													Warning you when interacting with a contract that has only recently been
													created onchain
												`
												: null,
										],
									)}
									{!value.contractTransactionWarning.privacyPreserving && (
										<Typography variant='body1'>
											However, in doing so, it leaks{' '}
											{commaListFormat([
												value.scamAlerts.contractTransactionWarning.leaksUserIp ? 'your IP' : null,
												value.scamAlerts.contractTransactionWarning.leaksUserAddress
													? 'your Ethereum address'
													: null,
												value.scamAlerts.contractTransactionWarning.leaksContractAddress
													? 'the contract address'
													: null,
											])}{' '}
											to an external service which can correlate them ahead of the transaction being
											submitted.
										</Typography>
									)}
									{toFullyQualified(value.scamAlerts.contractTransactionWarning.ref).length > 0 && (
										<ReferenceLinks
											references={toFullyQualified(value.scamAlerts.contractTransactionWarning.ref)}
											explanation='References:'
										/>
									)}
								</>
							) : (
								<Typography variant='body1'>
									{wallet.metadata.displayName} does not warn you when making arbitrary onchain
									transactions.
								</Typography>
							)}
						</li>
					)}
					{value.scamUrlWarning.required && (
						<li>
							{isSupported(value.scamAlerts.scamUrlWarning) ? (
								<>
									<Typography variant='body1'>
										{wallet.metadata.displayName} helps you stay safe when connecting to onchain
										apps by checking its URL against a set of known scam apps.
										{!value.scamUrlWarning.privacyPreserving && (
											<>
												{' '}
												However, in doing so, it leaks {commaListFormat(scamUrlLeaks)} to an
												external service{scamUrlLeaks.length > 1 && ' which can correlate them'}.
											</>
										)}
									</Typography>
									{toFullyQualified(value.scamAlerts.scamUrlWarning.ref).length > 0 && (
										<ReferenceLinks
											references={toFullyQualified(value.scamAlerts.scamUrlWarning.ref)}
										/>
									)}
								</>
							) : (
								<Typography variant='body1'>
									{wallet.metadata.displayName} does not warn you when making arbitrary onchain
									transactions.
								</Typography>
							)}
						</li>
					)}
				</ul>
			</div>
		</>
	)
}
